#
# ~/.bash_profile
#
## Start keyring, and add ssh keys to it. 

alias hibernate="systemctl hibernate && swaylock -f -i $HOME/.wallpaper/$(ls $HOME/.wallpaper/ | shuf -n 1)"
# gnome-keyring-daemon --start >> /dev/null
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
ssh-add $HOME/.ssh/bitbucket
ssh-add $HOME/.ssh/github

## Set $DISPLAY, since Wayland does not use Xorg style Display variable.
dbus-update-activation-environment --systemd DISPLAY

## Start NVM and Bash Auto-Complete.
# source /usr/share/nvm/init-nvm.sh
# source /usr/share/doc/pkgfile/command-not-found.bash
udiskie &

## Run .bashrc for this session.
[[ -f ~/.bashrc ]] && . ~/.bashrc


# Created by `pipx` on 2024-10-02 00:45:33
export PATH="$PATH:/home/rassawyer/.local/bin"
