" Don't try to be vi compatible
set nocompatible


" Turn on syntax highlighting
syntax on

" show line numbers
set number

" show file stats
set ruler

"use blink instead of beep for errors
set visualbell

" encoding
set encoding=utf-8

" Whitespace
set wrap
set textwidth=79
set formatoptions=tcqrn1
set tabstop=3
set shiftwidth=3
set softtabstop=3
set expandtab
set noshiftround

set matchpairs+=<:> " use % to jump between pairs

" Last line
set showmode
set showcmd

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch

" Formatting
map <leader>q gqip

" Visualize tabs and newlines
set listchars=tab:▸\ ,eol:¬

filetype plugin on
