#!/bin/bash

for i;
do

if [[ "$i" == "-h" ]]; then
        echo "Options include:"
        echo "-d - delete any existing logs in ~/.scripts/logs (backup logs)"
        echo "-h - display this help."
	exit 0
fi

if [[ "$i" == "-d" ]]; then
        rm -rfv ~/.scripts/logs/*

fi
done

echo "Backing up Deluge"
rsync -avz /home/rassawyer/Downloads/Deluge/ /run/media/rassawyer/2499B69425BF62E1/Backups/Deluge/ 2> /home/rassawyer/.scripts/logs/backup/deluge.txt

echo "Backing up Documents"
rsync -avz /home/rassawyer/Documents/ /run/media/rassawyer/2499B69425BF62E1/Backups/Documents/ 2> /home/rassawyer/.scripts/logs/backup/documents.txt

echo "Backing up Pictures"
rsync -avz /home/rassawyer/Pictures/ /run/media/rassawyer/2499B69425BF62E1/Backups/Pictures/ 2> /home/rassawyer/.scripts/logs/backup/pictures.txt

echo "Backing up Music"
rsync -avz /home/rassawyer/Music/ /run/media/rassawyer/2499B69425BF62E1/Backups/Music/ 2> /home/rassawyer/.scripts/logs/backup/music.txt

echo "Backing up /opt"
rsync -avz /opt/ /run/media/rassawyer/2499B69425BF62E1/Backups/opt/ 2> /home/rassawyer/.scripts/logs/backup/opt.txt

echo "Please see ~/.scripts/logs/backup/ for any errors."
