#!/bin/sh -xu

# Input Parameters from qBittorrent
ARG_PATH="$3/$2"
ARG_NAME="$2"
ARG_LABEL="${4:-N/A}"

# Explicitly define paths to avoid $HOME ambiguity
CONFIG_OUTPUT="/home/rassawyer/Media/Plex"
CONFIG_LOG="/home/rassawyer/Media/amc.log"
CONFIG_EXCLUDELIST="/home/rassawyer/Media/amc.txt"

# Run FileBot with proper environment and paths
/usr/bin/filebot -script fn:amc \
  --output "$CONFIG_OUTPUT" \
  --action duplicate \
  --format "{plex}" \
  --conflict auto \
  -non-strict \
  --log-file "$CONFIG_LOG" \
  --def skipExtract=y \
        subtitles=en \
        music=y \
        artwork=y \
        excludeList="$CONFIG_EXCLUDELIST" \
        ut_dir="$ARG_PATH" \
        ut_kind="multi" \
        ut_title="$ARG_NAME" \
        ut_label="$ARG_LABEL"

