#!/bin/sh -xu

filebot -script fn:amc --output "$HOME/Media/Plex" --action hardlink --format {plex} --conflict auto -non-strict "$HOME/Media/Plex/Downloads/Completed" --log-file amc.log --def excludesList=amc.txt subtitles=en clean=y unsorted=y music=y artwork=y 
