#! /bin/bash

REMOTE=$(git remote)

if [[ "$*" == "-s" ]]; then
	echo "Removing branches that have been merged."

	git fetch --prune | sed 's/\ -\ \[deleted\]\ \ \ \ \ \ \ \ \ (none)\ \ \ \ \ ->\ //gp' | xargs git branch -d

elif [[ "$*" == "-d" ]]; then
# first remove all branches that are "gone", or no longer exist. This feels like it should be done by the section above, but it wasn't working.
# there are innacuracies in the above command. Need more research figure out and fix

	git branch -vv | grep gone | sed -e 's/\ \ //' -e 's/\*\ //' -e 's/\ .*$//' | xargs git branch -d
	git branch -vv | grep -v $REMOTE | sed  -e 's/\ \ //' -e 's/\*\ //' -e 's/\ .*$//' | xargs git branch -d


elif [[ "$*" == "" ]]; then
	echo "gitclean -s removes merged branches; gitlean -d removes all branches that do not have a remote."
fi
