#!/bin/bash
echo "Checking for root..."
if [ "$(id -u)" != "0" ] ;
then
	echo "No root access found, elevating permissions..."
	[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
fi

echo "Password accepted; Proceeding"

echo "Backing up pacman database..."

tar -cjf /home/rassawyer/.bak/pacman-database.tar.bz2 /var/lib/pacman/local

echo "Removing unneeded packages..."

paccache -r

echo "Updating signature keys..."

pacman-key --populate archlinux

echo "Checking for updates..."

echo "Updating database..."

updatedb

echo "Optimizing database..."

pacman-optimize && sync

echo "Performing system upgrade..."

pacman -Syyu

sudo -k

echo "Optimize and update successful; exiting..."

pacman -Qqen > /home/rassawyer/.scripts/lists/official.list

pacman -Qq > /home/rassawyer/.scripts/lists/complete.list

comm -2 -3  /home/rassawyer/.scripts/lists/complete.list  /home/rassawyer/.scripts/lists/official.list  >  /home/rassawyer/.scripts/lists/aur.list

eval `ssh-agent`

ssh-add /home/rassawyer/.ssh/host4geeks

rsync -avz /home/rassawyer/.scripts/lists/ rassawyer@truegeekllc.com:/home/rassawyer/lists/

exit 0
