#!/bin/bash
echo "Checking for root..."
if [ "$(id -u)" != "0" ] ;
then
	echo "No root access found, elevating permissions..."
	[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
fi

echo "Password accepted; Proceeding"

echo "Backing up pacman database..."

tar -cjf /home/rassawyer/.bak/pacman-database.tar.bz2 /var/lib/pacman/local

echo "Removing unneeded packages..."

paccache -r

echo "Updating signature keys..."

pacman-key --populate archlinux

echo "Updating database..."

updatedb

echo "Optimizing database..."

pacman-optimize && sync

echo "Checking for updates and Performing system upgrade..."

pacman -Syyu

sudo -k

echo "Optimize and update successful; Generating updated package lists..."

pacman -Qqnt > /home/rassawyer/.scripts/lists/official.list

pacman -Qqm > /home/rassawyer/.scripts/lists/manual.list

echo "Pushing updated lists to remote"

syncup

exit 0
