#!/bin/bash

# This will run reflector on mirrorlist, getting the most recent mirrorlist, then copying it into the local location.

# Check for root access to write mirrorlist to pacman.d...

if [ "$(id -u)" != "0" ] ;
then
	echo "Not running as root, checking for elevated permissions..."
	[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
fi

# Backing up existing mirror list, in case of issue
mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak

# Get most recent mirrorlist...

curl -o /etc/pacman.d/mirrorlist https://www.archlinux.org/mirrorlist/all/
	
sudo -k


# Rank mirriorlist by date and speed...

reflector --verbose --country 'United States' -l 200 -f 200 -p https --sort rate --save /etc/pacman.d/mirrorlist
