#!/bin/bash
echo "Checking for root..."
if [ "$(id -u)" != "0" ] ;
then
	echo "No root access found, elevating permissions..."
	[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
fi

echo "Password accepted; Proceeding"

echo "Stopping cups.service"

systemctl stop org.cups.cupsd.service

echo "Restarting cups.service"

systemctl start org.cups.cupsd.service
