#!/bin/sh
killall swaybg
pidof swaybg > /dev/null
if [[ $? -ne 0 ]] ; then
	swaybg -i $HOME/.wallpaper/$(ls $HOME/.wallpaper/ | shuf -n1) -m fit &
	OLD_PID=$!
	echo $OLD_PID
	while true; do
		sleep 300
		swaybg -i $HOME/.wallpaper/$(ls $HOME/.wallpaper/ | shuf -n1) -m fit &
		NEXT_PID=$!
		sleep 1
		kill $OLD_PID
		OLD_PID=$NEXT_PID
	done
fi
