#! /bin/sh

if [[ "$(tmux ls | grep -c Chazak)" != 1 ]]; then

	## Create Tmux Server
	tmux new -s Chazak -d

	## Window #1
		tmux rename-window -t Chazak
		tmux send-keys 'cd ~/Code/Chazak/chazak/' C-m
		tmux send-keys 'npx nx serve pulse-web' C-m

		tmux split-window -h
		tmux send-keys 'cd ~/Code/Chazak/chazak/' C-m
		tmux send-keys 'nx run api:serve' C-m

	## Window #2
		tmux new-window -n  nnn
		tmux send-keys 'cd ~/Code/Chazak/chazak/' C-m
		tmux send-keys 'nnn' C-m

		tmux split-window -h
		tmux send-keys 'cd ~/Code/Chazak/chazak/' C-m
		tmux send-keys 'nnn' C-m

	## Window #3
		tmux new-window -n Git
		tmux send-keys 'cd ~/Code/Chazak/chazak/' C-m

		tmux split-window -h
		tmux send-keys 'cd ~/Code/Chazak/chazak/' C-m

	## Window #4 
		tmux new-window -n Local_Bash
		tmux split-window -h
		tmux send-keys 'ssh Android-Monster' C-m

	## Window #5
		tmux new-window -n IRC
		tmux send-keys 'irssi' C-m
fi

## Attach to Server
tmux attach -t Chazak

