#! /bin/sh

if [[ "$(tmux ls | grep -c Servers)" != 1 ]]; then

	## Create Tmux Server
	tmux new -s Servers -d

	## Window #1
		tmux rename-window -t Servers
		tmux send-keys 'cd ~/Code/Chazak/chazak/' C-m
		tmux send-keys 'npx nx serve pulse-web' C-m

		tmux split-window -h
		tmux send-keys 'cd ~/Code/Chazak/chazak/' C-m
		tmux send-keys 'nx run api:serve' C-m

fi

## Attach to Server
tmux attach -t Servers
	
