#! /bin/sh

if [[ "$(tmux ls | grep -c RRE)" != 1 ]]; then

## Create Tmux Server
tmux new -s RRE -d 

## Window #1
	tmux rename-window -t RRE Servers
 	tmux send-keys -t RRE 'cd ~/Code/RandR/rre-client' C-m 
	tmux send-keys -t RRE 'nrsd' C-m

	tmux split-window -h 
	tmux send-keys 'cd ~/Code/RandR/rre-server' C-m 
	tmux send-keys 'nrsd' C-m

## Window #2
	tmux new-window -n  Vim 	
	tmux send-keys 'cd ~/Code/RandR/' C-m 
	tmux send-keys 'nnn' C-m

	tmux split-window -h
	tmux send-keys 'cd ~/Code/RandR/' C-m 
	tmux send-keys 'nnn' C-m

## Window #3
	tmux new-window -n Git
	tmux send-keys 'cd ~/Code/RandR/rre-client' C-m

	tmux split-window -h
	tmux send-keys 'cd ~/Code/RandR/rre-server' C-m

## Window #4 
	tmux new-window -n Local_Bash
	tmux split-window -h
	tmux send-keys 'ssh Android-Monster' C-m

## Window #5
	tmux new-window -n IRC
	tmux send-keys 'irssi' C-m
fi

## Attach to Server
tmux attach -t RRE 
	
