#! /bin/sh

if [[ "$(tmux ls | grep -c Default)" != 1 ]]; then

	## Create Tmux Server
	tmux new -s Default -d

	## Window #1
		tmux rename-window -t Home
		# tmux send-keys 'cd ~/Code/Integro/ClickUp/integro' C-m
		# tmux send-keys '. github' C-m
		# tmux send-keys 'pnpm web'

		tmux split-window -h
		# tmux send-keys 'cd ~/Code/Integro/ClickUp/integro' C-m
		# tmux send-keys '. github' C-m
		# tmux send-keys 'pnpm api' 


	## Window #2
		tmux new-window -n  nnn
		## tmux send-keys 'cd ~/Code/Chazak/chazak/' C-m
		tmux send-keys 'nnn' C-m

		tmux split-window -h
		## tmux send-keys 'cd ~/Code/Chazak/chazak/' C-m
		tmux send-keys 'nnn' C-m

	## Window #3 
		tmux new-window -n Local_Bash
		tmux send-keys 'ssh Android_Monster' C-m

	## Window #4
		tmux new-window -n IRC
		tmux send-keys 'irssi' C-m
fi

# Attach to Server
tmux attach -t Default

