#! /bin/bash

if [[ "$*" == "+"  ]]; then
	pactl -- set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo +1%
	pactl -- set-sink-volume alsa_output.usb-Generic_USB_Audio_200901010001-00.HiFi__hw_Dock__sink +1%

elif [[ "$*" == "-" ]]; then
	pactl -- set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo -1%
	pactl -- set-sink-volume alsa_output.usb-Generic_USB_Audio_200901010001-00.HiFi__hw_Dock__sink -1%

elif [[ "$*" == "m"  ]]; then
	pactl -- set-sink-mute alsa_output.pci-0000_00_1f.3.analog-stereo toggle
	pactl -- set-sink-mute alsa_output.usb-Generic_USB_Audio_200901010001-00.HiFi__hw_Dock__sink toggle

fi
